### ISSUE TITLE
NullPointerException at com.iancaffey.steam.trade.TradeService.acceptOffer

### ISSUE THREAD

**Issue by Markus1812** [iitc/steam-bot#1]
Hello,

i am currently working on a java steam bot that accept trades that he gets.

Here is my code:

`steam = new Steam("<api key>", <my steam id>);`
`tradeService = steam.getTradeService();`
`TradeHistory tradeHistory = tradeService.getHistory(OfferType.RECEIVED, DescriptorDepth.MINIMAL, OfferDepth.CURRENT);`
`Offer[] offers = tradeHistory.getReceivedOffers();`

`for (Offer offer : offers) {`
`tradeService.acceptOffer(offer);`
`}`

and that is the error:
`Exception in thread "Thread-1" java.lang.NullPointerException`
`at com.iancaffey.steam.trade.TradeService.acceptOffer(TradeService.java:85)`

**Comment by iitc** [comment]
I've got to update the method to accept offers. Ever since steam removed official support for accepting trades through their REST API, there are some additional headers i need to set to bypass all the new restrictions. The NPE is coming from the request throwing a 411 response(due to incorrect headers) and a failure to parse the response into a `boolean`. As soon as I get a chance, I'll complete that method. All other methods should be fully working.

**Comment by iitc** [comment]
Steam has come down hard on bots, and as a result, I will not be fully implementing the method for now.
